Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: app.lambda_handler
      CodeUri: /Users/nakashima-toshio/codecommit/django-vue/djangoProject/sam-app/hello_world
      Runtime: python3.9
      Architectures:
        - x86_64