version: '3.8'

services:
  web:
    container_name: django_web
    build: ./app
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./dockerproject:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
