# Generated by Django 4.0.2 on 2022-02-12 08:21

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0002_remove_customuser_age'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', accounts.models.CustomUserManager()),
            ],
        ),
    ]
