version: '3'
services:
  ubuntu:
    restart: always
    image: ubuntu:latest
    container_name: ubuntu
    volumes:
      - ./home_data:/home
  ftp-server:
    image: stilliard/pure-ftpd:latest
    container_name: ftp-server
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      - ./docker/ftp/home:/home/ftpusers
      - ./docker/ftp/etc:/etc/ssl/private
    environment:
      - PUBLICHOST=localhost
      - FTP_USER_NAME=ftpuser
      - FTP_USER_PASS=password
      - FTP_USER_HOME=/home/ftpusers
      - ADDED_FLAGS="--tls=2"
    restart: always
volumes:
  home_data:
    driver: local
